In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, make_scorer, r2_score
import numpy as np
from sklearn.model_selection import cross_val_score
from datetime import datetime
from sklearn.preprocessing import StandardScaler

In [51]:
df = pd.read_csv('allData.csv', sep=',',low_memory=False)

In [52]:
df

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+-,Fantasy
0,20181016,Ben Simmons,Phi,Bos,87,105,42.45,7,14,0.500,...,12,15,8,4,2,3,5,19,-8,39.05
1,20181016,Joel Embiid,Phi,Bos,87,105,36.49,9,21,0.429,...,8,10,2,1,2,5,3,23,-8,26.05
2,20181016,Robert Covington,Phi,Bos,87,105,34.12,3,10,0.300,...,5,6,0,2,1,2,1,8,-9,11.90
3,20181016,Markelle Fultz,Phi,Bos,87,105,24.20,2,7,0.286,...,3,3,2,1,0,3,1,5,-16,3.10
4,20181016,Dario Šarić,Phi,Bos,87,105,22.55,3,8,0.375,...,6,6,1,0,0,3,5,6,-6,3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50123,20201011,Kyle Kuzma,LAL,Mia,106,93,21.56,1,4,0.250,...,1,1,0,0,0,1,3,2,2,-0.70
50124,20201011,Markieff Morris,LAL,Mia,106,93,16.38,1,4,0.250,...,1,2,0,0,0,0,2,3,1,2.40
50125,20201011,Jared Dudley,LAL,Mia,106,93,1.27,0,1,0.000,...,0,0,0,0,0,0,0,0,-4,-1.10
50126,20201011,Quinn Cook,LAL,Mia,106,93,1.27,0,1,0.000,...,0,0,0,0,0,0,0,0,-4,-1.10
50127,20201011,Dwight Howard,LAL,Mia,106,93,1.06,1,1,1.000,...,0,0,0,0,0,0,0,3,-4,2.40

In [53]:
df.columns

Index(['Date', 'Name', 'Team', 'Opp', 'score1', 'score2', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-', 'Fantasy'],
      dtype='object')

In [54]:
window = 10
df["mean_pts"] = df.groupby("Name")["PTS"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_orb"] = df.groupby("Name")["ORB"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_drb"] = df.groupby("Name")["DRB"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_ast"] = df.groupby("Name")["AST"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_stl"] = df.groupby("Name")["STL"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_blk"] = df.groupby("Name")["BLK"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_+-"] = df.groupby("Name")["+-"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_fga"] = df.groupby("Name")["FGA"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_fg"] = df.groupby("Name")["FG"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_fta"] = df.groupby("Name")["FTA"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_ft"] = df.groupby("Name")["FT"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_tov"] = df.groupby("Name")["TOV"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)
df["mean_pf"] = df.groupby("Name")["PF"].rolling(window).agg(lambda rows: rows[:window-1].mean()).reset_index(level = 0,drop = True)

KeyboardInterrupt:

In [55]:
window = 5
df["mean_pts"] = df.groupby("Name")["PTS"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_orb"] = df.groupby("Name")["ORB"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_drb"] = df.groupby("Name")["DRB"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_ast"] = df.groupby("Name")["AST"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_stl"] = df.groupby("Name")["STL"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_blk"] = df.groupby("Name")["BLK"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_+-"] = df.groupby("Name")["+-"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_fga"] = df.groupby("Name")["FGA"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_fg"] = df.groupby("Name")["FG"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_fta"] = df.groupby("Name")["FTA"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_ft"] = df.groupby("Name")["FT"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_tov"] = df.groupby("Name")["TOV"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)
df["mean_pf"] = df.groupby("Name")["PF"].expanding(window).agg(lambda rows: rows[:len(rows)-1].mean()).reset_index(level = 0,drop = True)

In [56]:
df["Fantasy_predict"] = 0.15 * df["mean_+-"] + df["mean_pts"] - 0.5*(df["mean_fga"] - df["mean_fg"] + df["mean_fta"] - df["mean_ft"]) + 0.75*df["mean_drb"] + df["mean_orb"] + df["mean_ast"] + 2*df["mean_stl"] + 2*df["mean_blk"] - 0.75*df["mean_tov"] - 0.5*df["mean_pf"]

In [57]:
df[df["Name"] == "Aaron Gordon"]

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,mean_stl,mean_blk,mean_+-,mean_fga,mean_fg,mean_fta,mean_ft,mean_tov,mean_pf,Fantasy_predict
119,20181017,Aaron Gordon,Orl,Mia,104,101,38.18,9,18,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,20181019,Aaron Gordon,Orl,Cha,88,120,24.54,2,9,0.222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,20181020,Aaron Gordon,Orl,Phi,115,116,32.07,7,12,0.583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,20181022,Aaron Gordon,Orl,Bos,93,90,38.35,5,11,0.455,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,20181025,Aaron Gordon,Orl,Por,114,128,28.25,6,11,0.545,...,0.750000,1.250000,2.250000,12.500000,5.750000,4.500000,3.000000,3.250000,2.500000,23.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47183,20200310,Aaron Gordon,Orl,Mem,120,115,31.36,3,8,0.375,...,0.797101,0.666667,-0.224638,13.036232,5.768116,3.391304,2.362319,1.898551,2.115942,21.230797
47402,20200731,Aaron Gordon,Orl,Bkn,128,118,26.00,2,5,0.400,...,0.798561,0.669065,-0.316547,13.000000,5.748201,3.381295,2.359712,1.899281,2.129496,21.209712
47713,20200802,Aaron Gordon,Orl,Sac,132,116,24.05,8,12,0.667,...,0.792857,0.664286,-0.142857,12.942857,5.721429,3.414286,2.385714,1.892857,2.121429,21.201786
47951,20200804,Aaron Gordon,Orl,Ind,109,120,33.00,8,15,0.533,...,0.787234,0.659574,0.021277,12.936170,5.737589,3.411348,2.390071,1.893617,2.120567,21.247872
48109,20200805,Aaron Gordon,Orl,Tor,99,109,20.20,3,9,0.333,...,0.788732,0.654930,-0.063380,12.950704,5.753521,3.415493,2.387324,1.887324,2.140845,21.247535

In [58]:
df_dropna = df.dropna()

In [59]:
np.sqrt(mean_squared_error(df_dropna["Fantasy"],df_dropna["Fantasy_predict"]))

8.705392244687076

In [60]:
df_dropna.columns

Index(['Date', 'Name', 'Team', 'Opp', 'score1', 'score2', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-', 'Fantasy', 'mean_pts',
       'mean_orb', 'mean_drb', 'mean_ast', 'mean_stl', 'mean_blk', 'mean_+-',
       'mean_fga', 'mean_fg', 'mean_fta', 'mean_ft', 'mean_tov', 'mean_pf',
       'Fantasy_predict'],
      dtype='object')

In [61]:
modeleReg=LinearRegression()
X = df_dropna[['mean_pts',
       'mean_orb', 'mean_drb', 'mean_ast', 'mean_stl', 'mean_blk', 'mean_+-',
       'mean_fga', 'mean_fg', 'mean_fta', 'mean_ft', 'mean_tov', 'mean_pf']]
Y = df_dropna["Fantasy"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(38052, 13)
(9513, 13)
(38052,)
(9513,)

In [62]:
lmodellineaire = LinearRegression()
lmodellineaire.fit(X_train, Y_train)

LinearRegression()

In [63]:
y_train_predict = lmodellineaire.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, y_train_predict)))
r2 = r2_score(Y_train, y_train_predict)

print('La performance du modèle sur la base dapprentissage')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))
print('\n')

La performance du modèle sur la base dapprentissage
--------------------------------------
Lerreur quadratique moyenne est 8.67230629600219
le score R2 est 0.41980634820177876

In [64]:
# model evaluation for testing set
y_test_predict = lmodellineaire.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))
r2 = r2_score(Y_test, y_test_predict)
 
print('La performance du modèle sur la base de test')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))

La performance du modèle sur la base de test
--------------------------------------
Lerreur quadratique moyenne est 8.631397625775076
le score R2 est 0.4163044739926892

In [71]:
scores = cross_val_score(lmodellineaire, X, Y, cv=5, scoring="neg_root_mean_squared_error")
print("Accuracy: %0.4f (+/- %0.4f)" % (scores.mean(), scores.std() * 2))

Accuracy: -8.6705 (+/- 0.5150)

In [187]:
df = pd.read_csv('allData.csv', sep=',',low_memory=False)

In [100]:
def weighted_stats(rows):
    rows = rows.reset_index(drop=True)
    return (rows[:window-1]*(np.array(rows.index.tolist()[:window-1])+1)).sum()

In [104]:
window = 11
df_mean = df.groupby("Name")[['FG', 'FGA','FT', 'FTA', 'ORB', 'DRB','AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-']].rolling(window).agg(weighted_stats).reset_index(level = 0,drop = True)

In [110]:
df_mean = df_mean.rename({'FG':'mean_FG', 'FGA':'mean_FGA','FT':'mean_FT', 'FTA':'mean_FTA', 'ORB':'mean_ORB', 'DRB':'mean_DRB','AST':'mean_AST', 'STL':'mean_STL', 'BLK':'mean_BLK', 'TOV':'mean_TOV', 'PF':'mean_PF', 'PTS':'mean_PTS', '+-':'mean_+-'},axis=1)

In [129]:
df_weighted_stats = pd.concat([df, df_mean], axis=1)
df_weighted_stats.columns

Index(['Date', 'Name', 'Team', 'Opp', 'score1', 'score2', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB',
       'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-', 'Fantasy', 'mean_FG',
       'mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST',
       'mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-'],
      dtype='object')

In [148]:
df_weighted_stats["prev_date"] = df_weighted_stats.groupby("Name")["Date"].shift(1)
df_weighted_stats = df_weighted_stats.dropna()
df_weighted_stats["prev_date"] = df_weighted_stats["prev_date"].astype(int)
df_weighted_stats

<ipython-input-148-fba8ce620019>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weighted_stats["prev_date"] = df_weighted_stats.groupby("Name")["Date"].shift(1)

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,mean_DRB,mean_AST,mean_STL,mean_BLK,mean_TOV,mean_PF,mean_PTS,mean_+-,prev_Date,prev_date
3825,20181110,Landry Shamet,Phi,Mem,106,112,42.30,2,13,0.154,...,0.618182,0.800000,0.563636,0.345455,0.545455,1.763636,9.163636,-4.472727,20181109.0,20181109
3826,20181110,Joel Embiid,Phi,Mem,106,112,39.22,4,15,0.267,...,11.872727,3.127273,0.163636,2.563636,3.545455,3.872727,29.381818,4.218182,20181109.0,20181109
3828,20181110,J.J. Redick,Phi,Mem,106,112,34.28,8,12,0.667,...,1.636364,3.872727,0.145455,0.072727,2.218182,1.218182,15.163636,1.090909,20181109.0,20181109
3829,20181110,Markelle Fultz,Phi,Mem,106,112,24.45,7,9,0.778,...,2.800000,3.290909,1.218182,0.145455,1.236364,3.127273,8.400000,4.090909,20181109.0,20181109
3833,20181110,Amir Johnson,Phi,Mem,106,112,13.38,3,4,0.750,...,2.145455,1.200000,0.218182,0.345455,1.363636,2.272727,3.690909,-2.363636,20181109.0,20181109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50123,20201011,Kyle Kuzma,LAL,Mia,106,93,21.56,1,4,0.250,...,1.472727,0.872727,0.418182,0.109091,0.981818,1.872727,12.109091,1.381818,20201006.0,20201006
50124,20201011,Markieff Morris,LAL,Mia,106,93,16.38,1,4,0.250,...,2.727273,1.181818,0.454545,0.054545,0.727273,2.600000,7.709091,2.000000,20201006.0,20201006
50125,20201011,Jared Dudley,LAL,Mia,106,93,1.27,0,1,0.000,...,1.090909,1.218182,0.909091,0.000000,0.436364,0.672727,1.345455,0.254545,20201004.0,20201004
50126,20201011,Quinn Cook,LAL,Mia,106,93,1.27,0,1,0.000,...,1.109091,1.472727,0.109091,0.163636,1.309091,0.872727,7.090909,-5.454545,20200824.0,20200824
50127,20201011,Dwight Howard,LAL,Mia,106,93,1.06,1,1,1.000,...,3.163636,0.636364,0.490909,0.163636,1.127273,2.690909,6.163636,-2.272727,20201006.0,20201006

In [151]:
df_weighted_stats["rest_days"] = df_weighted_stats.apply(lambda row: (datetime.strptime(str(row["Date"]), "%Y%m%d") - datetime.strptime(str(row["prev_date"]),"%Y%m%d")).days,axis=1)

In [152]:
df_weighted_stats

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,mean_AST,mean_STL,mean_BLK,mean_TOV,mean_PF,mean_PTS,mean_+-,prev_Date,prev_date,rest_days
3825,20181110,Landry Shamet,Phi,Mem,106,112,42.30,2,13,0.154,...,0.800000,0.563636,0.345455,0.545455,1.763636,9.163636,-4.472727,20181109.0,20181109,1
3826,20181110,Joel Embiid,Phi,Mem,106,112,39.22,4,15,0.267,...,3.127273,0.163636,2.563636,3.545455,3.872727,29.381818,4.218182,20181109.0,20181109,1
3828,20181110,J.J. Redick,Phi,Mem,106,112,34.28,8,12,0.667,...,3.872727,0.145455,0.072727,2.218182,1.218182,15.163636,1.090909,20181109.0,20181109,1
3829,20181110,Markelle Fultz,Phi,Mem,106,112,24.45,7,9,0.778,...,3.290909,1.218182,0.145455,1.236364,3.127273,8.400000,4.090909,20181109.0,20181109,1
3833,20181110,Amir Johnson,Phi,Mem,106,112,13.38,3,4,0.750,...,1.200000,0.218182,0.345455,1.363636,2.272727,3.690909,-2.363636,20181109.0,20181109,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50123,20201011,Kyle Kuzma,LAL,Mia,106,93,21.56,1,4,0.250,...,0.872727,0.418182,0.109091,0.981818,1.872727,12.109091,1.381818,20201006.0,20201006,5
50124,20201011,Markieff Morris,LAL,Mia,106,93,16.38,1,4,0.250,...,1.181818,0.454545,0.054545,0.727273,2.600000,7.709091,2.000000,20201006.0,20201006,5
50125,20201011,Jared Dudley,LAL,Mia,106,93,1.27,0,1,0.000,...,1.218182,0.909091,0.000000,0.436364,0.672727,1.345455,0.254545,20201004.0,20201004,7
50126,20201011,Quinn Cook,LAL,Mia,106,93,1.27,0,1,0.000,...,1.472727,0.109091,0.163636,1.309091,0.872727,7.090909,-5.454545,20200824.0,20200824,48
50127,20201011,Dwight Howard,LAL,Mia,106,93,1.06,1,1,1.000,...,0.636364,0.490909,0.163636,1.127273,2.690909,6.163636,-2.272727,20201006.0,20201006,5

In [174]:
modeleReg=LinearRegression()
X = df_weighted_stats[['mean_FG',
       'mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST',
       'mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-',"rest_days"]]

Y = df_weighted_stats["Fantasy"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(33890, 14)
(8473, 14)
(33890,)
(8473,)

In [175]:
lmodellineaire = LinearRegression()
lmodellineaire.fit(X_train, Y_train)

LinearRegression()

In [176]:
y_train_predict = lmodellineaire.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, y_train_predict)))
r2 = r2_score(Y_train, y_train_predict)

print('La performance du modèle sur la base dapprentissage')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))
print('\n')

La performance du modèle sur la base dapprentissage
--------------------------------------
Lerreur quadratique moyenne est 8.578396837039673
le score R2 est 0.42892721776237497

In [177]:
# model evaluation for testing set
y_test_predict = lmodellineaire.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))
r2 = r2_score(Y_test, y_test_predict)
 
print('La performance du modèle sur la base de test')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))

La performance du modèle sur la base de test
--------------------------------------
Lerreur quadratique moyenne est 8.72927535047804
le score R2 est 0.43925209939153

In [178]:
lmodellineaire.coef_

array([ 1.06492154,  0.30651198,  1.00040066, -0.11785168,  0.64238504,
        0.73120386,  0.70372059,  0.94045703,  1.61977383,  0.29581326,
       -0.13159494, -0.09851083,  0.04637546, -0.01222333])

In [179]:
df_weighted_stats["prediction"] = lmodellineaire.predict(df_weighted_stats[['mean_FG',
       'mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST',
       'mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-',"rest_days"]])

In [183]:
df_weighted_stats[df_weighted_stats["Date"]==20200114].sort_values(by="prediction",ascending=False)

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,mean_STL,mean_BLK,mean_TOV,mean_PF,mean_PTS,mean_+-,prev_Date,prev_date,rest_days,prediction
39615,20200114,James Harden,Hou,Mem,110,121,39.08,13,37,0.351,...,1.345455,1.327273,5.236364,2.527273,33.800000,2.381818,20200111.0,20200111,3,38.214470
39659,20200114,Luka Dončić,Dal,GSW,124,97,27.01,8,19,0.421,...,0.490909,0.218182,4.690909,2.818182,28.527273,4.236364,20200111.0,20200111,3,36.490181
39587,20200114,Trae Young,Atl,Pho,123,110,37.47,11,25,0.440,...,1.000000,0.163636,4.890909,2.018182,30.509091,-3.345455,20200110.0,20200110,4,34.075360
39648,20200114,Giannis Antetokounmpo,Mil,NYK,128,102,21.26,12,17,0.706,...,0.963636,0.436364,2.600000,3.327273,25.472727,5.218182,20200111.0,20200111,3,33.815069
39694,20200114,Kawhi Leonard,LAC,Cle,128,103,28.44,14,22,0.636,...,2.327273,0.290909,3.145455,1.927273,26.709091,1.745455,20200112.0,20200112,2,31.669062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39702,20200114,Jerome Robinson,LAC,Cle,128,103,15.48,3,6,0.500,...,0.090909,0.000000,0.545455,1.200000,1.945455,1.000000,20200112.0,20200112,2,3.550873
39623,20200114,Tyson Chandler,Hou,Mem,110,121,2.27,0,0,0.000,...,0.236364,0.163636,0.218182,1.200000,0.890909,-0.600000,20200111.0,20200111,3,3.530788
39658,20200114,D.J. Wilson,Mil,NYK,128,102,9.56,1,4,0.250,...,0.000000,0.290909,0.145455,0.127273,0.509091,-1.781818,20200111.0,20200111,3,3.456405
39704,20200114,Terance Mann,LAC,Cle,128,103,12.00,0,4,0.000,...,0.109091,0.181818,0.290909,1.036364,1.400000,-2.254545,20200112.0,20200112,2,3.454932
39670,20200114,Courtney Lee,Dal,GSW,124,97,8.12,0,1,0.000,...,0.018182,0.181818,0.309091,0.581818,3.381818,1.236364,20200102.0,20200102,12,3.432558

In [189]:
df_weighted_stats[df_weighted_stats["Date"]==20200114].sort_values(by="Name",ascending=False).to_csv("20200114.csv", sep=',',index=False)

In [36]:
df = pd.read_csv('allData.csv', sep=',',low_memory=False)

In [37]:
df

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+-,Fantasy
0,20181016,Ben Simmons,Phi,Bos,87,105,42.45,7,14,0.500,...,12,15,8,4,2,3,5,19,-8,39.05
1,20181016,Joel Embiid,Phi,Bos,87,105,36.49,9,21,0.429,...,8,10,2,1,2,5,3,23,-8,26.05
2,20181016,Robert Covington,Phi,Bos,87,105,34.12,3,10,0.300,...,5,6,0,2,1,2,1,8,-9,11.90
3,20181016,Markelle Fultz,Phi,Bos,87,105,24.20,2,7,0.286,...,3,3,2,1,0,3,1,5,-16,3.10
4,20181016,Dario Šarić,Phi,Bos,87,105,22.55,3,8,0.375,...,6,6,1,0,0,3,5,6,-6,3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50123,20201011,Kyle Kuzma,LAL,Mia,106,93,21.56,1,4,0.250,...,1,1,0,0,0,1,3,2,2,-0.70
50124,20201011,Markieff Morris,LAL,Mia,106,93,16.38,1,4,0.250,...,1,2,0,0,0,0,2,3,1,2.40
50125,20201011,Jared Dudley,LAL,Mia,106,93,1.27,0,1,0.000,...,0,0,0,0,0,0,0,0,-4,-1.10
50126,20201011,Quinn Cook,LAL,Mia,106,93,1.27,0,1,0.000,...,0,0,0,0,0,0,0,0,-4,-1.10
50127,20201011,Dwight Howard,LAL,Mia,106,93,1.06,1,1,1.000,...,0,0,0,0,0,0,0,3,-4,2.40

In [38]:
window = 11

df_sum = df.groupby("Name")[['MP','FG', 'FGA','FT', 'FTA', 'ORB', 'DRB','AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-']].rolling(window).agg(lambda rows: rows[:window-1].sum()).reset_index(level = 0,drop = True)

In [39]:
df_sum = df_sum[['FG', 'FGA','FT', 'FTA', 'ORB', 'DRB','AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', '+-']].apply(lambda row: row/df_sum["MP"])

In [40]:
df_sum

,FG,FGA,FT,FTA,ORB,DRB,AST,STL,BLK,TOV,PF,PTS,+-
119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10500,0.080617,0.213060,0.011517,0.011517,0.011517,0.092134,0.034550,0.034550,0.000000,0.034550,0.086376,0.224577,-0.051825
15937,0.081931,0.218484,0.021848,0.021848,0.010924,0.087393,0.027310,0.032773,0.010924,0.027310,0.087393,0.240332,-0.038235
16383,0.094118,0.235294,0.023529,0.023529,0.011765,0.094118,0.023529,0.017647,0.011765,0.023529,0.094118,0.276471,0.041176
17205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23830,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df_sum = df_sum.rename({'FG':'mean_FG', 'FGA':'mean_FGA','FT':'mean_FT', 'FTA':'mean_FTA', 'ORB':'mean_ORB', 'DRB':'mean_DRB','AST':'mean_AST', 'STL':'mean_STL', 'BLK':'mean_BLK', 'TOV':'mean_TOV', 'PF':'mean_PF', 'PTS':'mean_PTS', '+-':'mean_+-'},axis=1)

In [42]:
df_final = pd.concat([df,df_sum],axis=1)

In [43]:
df_final

,Date,Name,Team,Opp,score1,score2,MP,FG,FGA,FG%,...,mean_FTA,mean_ORB,mean_DRB,mean_AST,mean_STL,mean_BLK,mean_TOV,mean_PF,mean_PTS,mean_+-
0,20181016,Ben Simmons,Phi,Bos,87,105,42.45,7,14,0.500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20181016,Joel Embiid,Phi,Bos,87,105,36.49,9,21,0.429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20181016,Robert Covington,Phi,Bos,87,105,34.12,3,10,0.300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20181016,Markelle Fultz,Phi,Bos,87,105,24.20,2,7,0.286,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20181016,Dario Šarić,Phi,Bos,87,105,22.55,3,8,0.375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50123,20201011,Kyle Kuzma,LAL,Mia,106,93,21.56,1,4,0.250,...,0.077184,0.034304,0.085760,0.047168,0.034304,0.008576,0.047168,0.081472,0.548862,0.085760
50124,20201011,Markieff Morris,LAL,Mia,106,93,16.38,1,4,0.250,...,0.030108,0.040145,0.145524,0.050181,0.020072,0.005018,0.030108,0.125452,0.366319,0.000000
50125,20201011,Jared Dudley,LAL,Mia,106,93,1.27,0,1,0.000,...,0.000000,0.014537,0.159907,0.145370,0.101759,0.000000,0.043611,0.072685,0.145370,0.101759
50126,20201011,Quinn Cook,LAL,Mia,106,93,1.27,0,1,0.000,...,0.049493,0.032995,0.074239,0.090737,0.008249,0.008249,0.082488,0.065990,0.420688,-0.313454
50127,20201011,Dwight Howard,LAL,Mia,106,93,1.06,1,1,1.000,...,0.219245,0.164434,0.274056,0.036541,0.030451,0.012180,0.085262,0.182704,0.426309,-0.152253

In [45]:
df_stat_predict = df_final[['mean_FG','mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST','mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-']].apply(lambda row: row*df_final["MP"])

In [96]:
df_final = pd.concat([df,df_stat_predict],axis=1)

In [114]:
df_adv_fantasy = df_final.groupby(["Opp","Date"])["Fantasy"].sum()

In [155]:
df_final["start_date"] = df_final.groupby(["Opp","Date"])["Date"].rolling(11).apply(lambda rows: rows.index.tolist()[0]).reset_index(level=[0,1],drop=True)

In [164]:
df_final["start_date"][45000]

19644.0

In [154]:
df_adv_fantasy.loc['Atl'].index[0]

20181017

In [47]:
df_final = df_final.dropna()

In [54]:
df_final["diff_score"] = df_final["score1"] - df_final["score2"]

In [95]:
X = df_final[['mean_FG',
       'mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST',
       'mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-']]

Y = df_final["Fantasy"]

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(35220, 13)
(8805, 13)
(35220,)
(8805,)

In [92]:
lmodellineaire = LinearRegression()
lmodellineaire.fit(X_train, Y_train)

LinearRegression()

In [93]:
y_train_predict = lmodellineaire.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, y_train_predict)))
r2 = r2_score(Y_train, y_train_predict)

print('La performance du modèle sur la base dapprentissage')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))
print('\n')

La performance du modèle sur la base dapprentissage
--------------------------------------
Lerreur quadratique moyenne est 6.7484764096690855
le score R2 est 0.6487019625506905

In [94]:
# model evaluation for testing set
y_test_predict = lmodellineaire.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))
r2 = r2_score(Y_test, y_test_predict)
 
print('La performance du modèle sur la base de test')
print('--------------------------------------')
print('Lerreur quadratique moyenne est {}'.format(rmse))
print('le score R2 est {}'.format(r2))

La performance du modèle sur la base de test
--------------------------------------
Lerreur quadratique moyenne est 6.73526994167156
le score R2 est 0.6533028171913288

In [79]:
lmodellineaire.coef_

array([ 0.35489678,  0.46679173,  0.5735763 , -0.13973806,  0.94004667,
        0.80848124,  0.89280516,  1.05942571,  1.78568963, -0.09575922,
        0.43527185,  0.16479802,  0.00910781])

In [81]:
df_final["prediction"] = lmodellineaire.predict(df_final[['mean_FG',
       'mean_FGA', 'mean_FT', 'mean_FTA', 'mean_ORB', 'mean_DRB', 'mean_AST',
       'mean_STL', 'mean_BLK', 'mean_TOV', 'mean_PF', 'mean_PTS', 'mean_+-']])

In [82]:
df_final[df_final["Date"]==20200114].to_csv("20200114.csv", sep=',',index=False)